Conditioning qgis_clickfu
nextgis/qgis_clickfu pull request #13
Opened 2024-07-18 14:02 UTC by RemeshevskiyValeriy

2024-08-20 04:15 UTC, ivanbarsukov requested changes

2024-08-20 04:15 UTC, ivanbarsukov commented on pyproject.toml
> +"tests/test_*.py" = ["E402"]
Тут нет тестов

2024-08-20 04:15 UTC, ivanbarsukov commented on src/clickfu/about_dialog.py
> +        for key, value in list(replacemens.items()):
Зачем в list?

2024-08-20 04:15 UTC, ivanbarsukov commented on flickrMap.py
Скорее всего, забыл воспользоваться git mv и получилось как два независимых файла

2024-08-20 04:15 UTC, ivanbarsukov commented on src/clickfu/flickrMap.py
> +        cfAction.__init__(self, self.name(), iface)
Лучше будет через `super()`

2024-08-20 21:56 UTC, RemeshevskiyValeriy commented on pyproject.toml
> +builtins-ignorelist = ["id"]
https://docs.astral.sh/ruff/settings/#lint_flake8-builtins_builtins-ignorelist

2024-08-20 21:57 UTC, RemeshevskiyValeriy commented on src/clickfu/about_dialog.py
> +        for key, value in list(replacemens.items()):
"2to3" завернул в list

2024-08-21 04:05 UTC, ivanbarsukov commented on pyproject.toml
> +builtins-ignorelist = ["id"]
Смысл опции понятен) Почему мы решили её использовать?

2024-08-21 04:06 UTC, ivanbarsukov commented on src/clickfu/about_dialog.py
> +        for key, value in list(replacemens.items()):
Понял. Убери, пожалуйста, это лишнее преобразование

2024-08-21 06:12 UTC, RemeshevskiyValeriy commented on pyproject.toml
> +builtins-ignorelist = ["id"]
Имя аргумента "id" выглядело весьма лаконично, не хотелось менять на условный "identifier")))

2024-08-21 06:14 UTC, ivanbarsukov commented on pyproject.toml
> +builtins-ignorelist = ["id"]
Понимаю, но это из тех правил, которые лучше не игнорировать, так как отладить может быть проблематично

2024-09-04 15:17 UTC, merged